# Generated by Django 4.1.3 on 2023-01-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_countrymodel_capital_and_more'),
        ('users', '0002_alter_usermodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='countries.countrymodel', verbose_name='where are you from?'),
        ),
    ]
