# Generated by Django 4.1.3 on 2023-01-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioma', '0001_initial'),
        ('countries', '0004_alter_countrymodel_capital_and_more'),
        ('users', '0003_alter_usermodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='biomes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioma.biomemodel', verbose_name='places u like to travel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='countries.countrymodel'),
        ),
    ]
