# Generated by Django 4.1.3 on 2023-01-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pais')),
                ('english_name', models.CharField(max_length=50, verbose_name='Pais en ingles')),
                ('capital', models.CharField(max_length=50, verbose_name='Capital')),
                ('continent', models.CharField(max_length=50, verbose_name='Continente')),
                ('main_language', models.CharField(max_length=50, verbose_name='Idioma Principal')),
                ('currency', models.CharField(max_length=50, verbose_name='Moneda')),
                ('currency_symbol', models.CharField(max_length=50, verbose_name='Simbolo de Moneda')),
            ],
        ),
    ]
