# Generated by Django 4.1.3 on 2023-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_countrymodel_id_countrymodel_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='main_language',
            new_name='languages',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='english_name',
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='flagPNG',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='flagSVG',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='official',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='currency',
            field=models.CharField(max_length=100, verbose_name='Moneda'),
        ),
    ]
