# Generated by Django 4.1.3 on 2023-01-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_rename_main_language_countrymodel_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='capital',
            field=models.CharField(blank=True, max_length=150, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=models.CharField(max_length=150, verbose_name='Continente'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='currency',
            field=models.CharField(blank=True, max_length=150, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='flagPNG',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='flagSVG',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='languages',
            field=models.CharField(max_length=150, verbose_name='Idioma Principal'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='official',
            field=models.CharField(max_length=150),
        ),
    ]
